### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by zargogo** [mathieugouin/tradesim#22]
I have all the prerequisites but I don't know which of all these scripts is the main script? Sorry if it's a very newby question

**Comment by mathieugouin** [comment]
Hey, thanks for your interest.

Here is a very quick response.  Will try to get more details later on.

* Download the stocks you are interested.  Have a look at download_historical_data.sh (tweak it to your needs)
* Then, the main program is tradesim.py.  Please note that this is is still a big work in progress...

**Comment by zargogo** [comment]
Thank you so much for the quick response!

Unfortunately, after downloading the historical data and running tadesim.py, I get the following error:
```

load_data()
plot_test()
simulate()
Initial cash 100000.0
Traceback (most recent call last):
  File "/Users/zargogo/Downloads/tradesim-master2/tradesim.py", line 213, in <module>
    _main()
  File "/Users/zargogo/Downloads/tradesim-master2/tradesim.py", line 208, in _main
    simulate()
  File "/Users/zargogo/Downloads/tradesim-master2/tradesim.py", line 71, in simulate
    for i in range(len(df_prices)):
TypeError: object of type 'NoneType' has no len()

```

**Comment by mathieugouin** [comment]
Depending on where you stored your historical data, you might want to update this line in tradesim.py (near the top of the file):

`data_dir = './stock_db/qt'`

You probably downloaded the data somewhere else.  Also confirm that in your download folder, you have csv files corresponding to the stocks you are interested in analyzing.

Hope this helps!

**Comment by zargogo** [comment]
Thank you, it works :)
