### ISSUE TITLE
Duplicated index from yahoo download

### ISSUE THREAD

**Issue by mathieugouin** [mathieugouin/tradesim#38]
When download was tried on 2022-03-13, the following was downloaded for SPY:

Command:
`python -m coverage run -a get_yahoo_finance_data.py --concurrent 1 --file stock_db/test.txt --dir ./stock_db/test --startdate 20100101 --verbose`

```
Date,Open,High,Low,Close,Adj Close,Volume
2010-01-04,112.370003,113.389999,111.510002,113.330002,89.889221,118944600
....
2022-03-11,428.119995,428.769989,419.529999,420.070007,420.070007,95529600
2022-03-11,428.119995,428.769989,419.529999,420.070007,420.070007,95636277
```

**Comment by mathieugouin** [comment]
A duplicate index at 2022-03-11 with different volume !!!

**Comment by mathieugouin** [comment]
Refer to https://github.com/ranaroussi/yfinance/issues/573

**Comment by mathieugouin** [comment]
[VUN.TO_2022-03-13_duplicate.csv](https://github.com/mathieugouin/tradesim/files/8240553/VUN.TO_2022-03-13_duplicate.csv)

**Comment by ValueRaider** [comment]
Is this still happening?
